### ISSUE TITLE
Server time in past with 2h

### ISSUE THREAD

**Issue by Mr-Vinti** [vmck/acs-interface#89] opened 2019-10-28 19:21 UTC
Might prompt errors, for example submission 1350(bottom)

**Comment by mgax** [comment] 2019-10-29 10:28
Please link to the relevant page (https://v2.vmchecker.cs.pub.ro/submission/1350) and quote the text you're talking about:
```
make: Warning: File 'ip.c' has modification time 5019 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
```

The next submission, https://v2.vmchecker.cs.pub.ro/submission/1351, doesn't display that message. I suspect the problem was caused by the timestamps zip file, not by the server time, which is now `Tue Oct 29 10:27:49 UTC 2019`, about right.

**Comment by mgax** [comment] 2019-10-30 19:41
Was fixed in django settings

**Closed by mgax** 2019-10-30 19:41 UTC
